name: demo_api
description: A simple Dart API
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  envied: ^1.0.0

dev_dependencies:
  http: ^1.1.0
  test: ^1.24.0
  lints: ^2.1.0
  build_runner: ^2.4.14
  envied_generator: ^1.0.0
